=== zelon/xml-xsd-validator/xml-xsd-validator/xml-xsd-validator/test.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="book">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="author">
        <xs:complexType>
          <xs:all>
            <xs:element name="name" type="xs:string" />
            <xs:element name="address" type="xs:string" />
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element name="chapter_list">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="chapter" minOccurs="1" maxOccurs="unbounded">
              <xs:complexType>
                <xs:all>
                  <xs:element name="chapter_title" type="xs:string" />
                  <xs:element name="page_number" type="xs:positiveInteger" />
                  <xs:element name="chapter_sub_title" type="xs:string" minOccurs="0"/>
                  <xs:element name="comment_list">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="comment" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:attribute name="name" type="xs:string" use="required" />
                            <xs:attribute name="content" type="xs:string" />
                            <xs:attribute name="from">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="alading" />
                                  <xs:enumeration value="yes23" />
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:all>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== zelon/xml-xsd-validator/xml-xsd-validator/xml-xsd-validator/test.xml
<?xml version="1.0" encoding="utf-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test.xsd">
  <author>
    <name>Hong Gil-dong</name>
    <address>Korea</address>
  </author>
  <chapter_list>
    <chapter>
      <chapter_title>The First Chapter</chapter_title>
      <chapter_sub_title></chapter_sub_title>
      <page_number>10</page_number>
      <comment_list>
        <comment name="zelon" content="This is good" from="alading" />
        <comment name="mk" content="This is not good" from="yes23" />
      </comment_list>
    </chapter>
  </chapter_list>
</book>
